Django_web/solayof/hello/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet")
]

Django_web/solayof/newyear/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index"),
]

Django_web/solayof/solayof/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("newyear/", include("newyear.urls")),
    path("task/", include("task.urls")),
]

Django_web/solayof/task/urls.py
from django.urls import path
from . import views

app_name = "task"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Django_web/solayof/hello/models.py
from django.db import models

# Create your models here.

Django_web/solayof/newyear/models.py
from django.db import models

# Create your models here.

Django_web/solayof/task/models.py
from django.db import models

# Create your models here.

Django_web/solayof/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def greet(request, name):
    return render(request,"hello/greet.html", {"name": name.capitalize()})

def ayo(request):
    return render(request, "hello/ayo.html")

Django_web/solayof/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

Django_web/solayof/task/views.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse


class   NewTaskForm(forms.Form):
    task = forms.CharField(label="new Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=10)
# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "task/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request, "task/add.html", {
                "form":form
            })
    return render(request, "task/add.html", {
        "form":NewTaskForm()
    })

Django_web/solayof/hello/templates/hello/ayo.html
<1DOCTYPE html>
<html lang="en">
    <body>
        <p> Ayo teat</p>
    </body>
</html>

Django_web/solayof/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Greeting</title>
    </head>
    <body>
        <h>Welcome, {{name}}.</h>
    </body>
</html>

Django_web/solayof/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <title> Home Page</title>
    </head>
    <body>
        <p>Welcome, to Solayof.</p>
    </body>
</html>

Django_web/solayof/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE  html>
<html lang="en">
    <head>
        <link href="{% static 'newyear/style.css' %}", rel="stylesheet">
        <title> New Year</title>
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

Django_web/solayof/task/templates/task/add.html
{% extends "task/layout.html" %}
{% block body %}
    <h1>Add Task</h1>
    <form action="{% url "task:add" %}" method="post">
        {% csrf_token %}
    {{ form }}
    <input type="submit">
    </form>
    <a href="{% url "task:index" %}">View Task</a>
{% endblock %}

Django_web/solayof/task/templates/task/index.html
{% extends "task/layout.html" %}
{% block body %}
    <h1>Task</h1>
    <ul>
        {% for ta in tasks %}
        <li>{{ta}}</li>
        {% empty %}
            <li>No Task</li>
        {% endfor %}
        
    </ul>
    <a href="{% url "task:add" %}">Add a New Task</a>
{% endblock %}

Django_web/solayof/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Task</title>
    </head>
    <body>
        {% block  body %}
        {% endblock  %}
    </body>
</html>